[package]
name = "lfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"] }
littlefs2 = "0.3"
anyhow = "1"
x509-parser = "0.13"
pem = "1"
sha2 = "0.10"
